import Foundation

let commentMarker              : Scalar = "#"
let hexPrefix                  : Scalar = "u"
let unicodeHead                : Scalar = "U"
let underscore                 : Scalar = "_"
let unionOperator              : Scalar = "|"
let zeroOrMoreOperator         : Scalar = "*"
let oneOrMoreOperator          : Scalar = "+"
let zeroOrOneOperator          : Scalar = "?"
let lineTailOperator           : Scalar = "$"
let lineHeadOperator           : Scalar = "^"
let characterLiteralMarker     : Scalar = "'"
let groupLeftDelimiter         : Scalar = "("
let groupRightDelimiter        : Scalar = ")"
let bracketedSetLeftDelimiter  : Scalar = "{"
let bracketedSetRightDelimiter : Scalar = "}"
let rangeSeparator             : Scalar = "-"
let ruleTerminator             : Scalar = ";"
let stringDelimiter            : Scalar = "\""
let setMinus                   : Scalar = "\\"
let setSeparator               : Scalar = ","
