import Foundation

let hash             : Scalar = "#"
let bar              : Scalar = "|"
let star             : Scalar = "*"
let plus             : Scalar = "+"
let question         : Scalar = "?"
let period           : Scalar = "."
let dollar           : Scalar = "$"
let caret            : Scalar = "^"
let quote            : Scalar = "'"
let leftParenthesis  : Scalar = "("
let rightParenthesis : Scalar = ")"
let leftBracket      : Scalar = "["
let rightBracket     : Scalar = "]"
let minus            : Scalar = "-"
let semicolon        : Scalar = ";"
let underscore       : Scalar = "_"
